changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: 新功能
      labels:
        - enhancement
        - feature
    - title: 修复
      labels:
        - bug
        - fix
    - title: 依赖与维护
      labels:
        - dependencies
        - maintenance
    - title: 其他改动
      labels:
        - "*"
